"""
AIQE Browser Execution Agent.

Executes Playwright browser tests generated by the
Automation Generator and captures evidence.

Responsibilities:
    - Launch Playwright browser (Chromium/Firefox/WebKit)
    - Execute generated Playwright scripts
    - Capture screenshots on failure
    - Record video of test sessions (if enabled)
    - Collect browser console logs
    - Collect network request/response logs
    - Collect accessibility tree snapshots
    - Report pass/fail for each test
    - Write results to shared memory for Bug Analysis

Security note:
    Browser execution runs against the application under test.
    AIQE never executes JavaScript from untrusted sources.
    Screenshots and videos may contain sensitive data —
    they are stored only in the isolated workflow workspace.

Tier: 2 (Execution)
Dependencies: automation_generator
Memory Reads:
    - automation_generator.playwright_scripts
    - project_analysis.result
Memory Writes:
    - browser_execution.results
    - browser_execution.failed_tests
"""

from __future__ import annotations

import json
import time
import uuid
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from aiqe.agents.base import BaseAgent
from aiqe.agents.types import AgentInput, AgentOutput
from aiqe.memory.schema import MemoryKeys
from aiqe.shared.logging import get_logger
from aiqe.shared.utils import Timer

logger = get_logger(__name__)


@dataclass
class BrowserTestResult:
    """Result of a single browser test execution."""
    test_id: str = field(default_factory=lambda: f"bt_{uuid.uuid4().hex[:8]}")
    test_name: str = ""
    script_file: str = ""
    feature: str = ""
    passed: bool = False
    duration_seconds: float = 0.0
    error: str | None = None
    screenshot_path: str | None = None
    video_path: str | None = None
    console_logs: list[str] = field(default_factory=list)
    network_logs: list[dict[str, Any]] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "test_id": self.test_id,
            "test_name": self.test_name,
            "script_file": self.script_file,
            "feature": self.feature,
            "passed": self.passed,
            "duration_seconds": self.duration_seconds,
            "error": self.error,
            "screenshot_path": self.screenshot_path,
            "video_path": self.video_path,
            "console_logs": self.console_logs[:20],
            "network_logs_count": len(self.network_logs),
        }


class BrowserExecutionOutput(AgentOutput):
    """Output from the Browser Execution Agent."""

    def __init__(self) -> None:
        super().__init__()
        self.results: list[dict[str, Any]] = []
        self.failed_tests: list[dict[str, Any]] = []
        self.total_executed: int = 0
        self.total_passed: int = 0
        self.total_failed: int = 0
        self.pass_rate: float = 0.0
        self.screenshots: list[str] = []
        self.execution_mode: str = "dry_run"

    def to_dict(self) -> dict[str, Any]:
        base = super().to_dict()
        return {
            **base,
            "results": self.results,
            "failed_tests": self.failed_tests,
            "total_executed": self.total_executed,
            "total_passed": self.total_passed,
            "total_failed": self.total_failed,
            "pass_rate": self.pass_rate,
            "screenshots": self.screenshots,
            "execution_mode": self.execution_mode,
        }


class BrowserExecutionInput(AgentInput):
    """Input for the Browser Execution Agent."""
    base_url: str = "http://localhost:8000"
    browser_type: str = "chromium"
    headless: bool = True
    capture_screenshots: bool = True
    capture_video: bool = False
    timeout_seconds: int = 30
    max_retries: int = 1


class BrowserExecutionAgent(BaseAgent):
    """
    Browser Execution Agent — Tier 2.

    Runs Playwright browser tests and collects evidence.
    Falls back to dry-run mode when Playwright is not available
    or when no application is running at base_url.
    """

    NAME = "browser_execution"
    DESCRIPTION = (
        "Executes Playwright browser tests, captures screenshots, "
        "videos, console logs, and network traces as evidence."
    )
    TIER = 2
    DEPENDENCIES = ["automation_generator"]

    def __init__(
        self,
        memory_store: Any = None,
        gateway: Any = None,
    ) -> None:
        self._memory = memory_store
        self._gateway = gateway

    async def run_impl(self, input_data: AgentInput) -> BrowserExecutionOutput:
        """Execute browser tests."""
        assert isinstance(input_data, BrowserExecutionInput), (
            f"Expected BrowserExecutionInput, got {type(input_data).__name__}"
        )

        output = BrowserExecutionOutput()

        # Load generated scripts from memory
        playwright_scripts: list[dict[str, Any]] = []
        if self._memory:
            playwright_scripts = await self._memory.get(
                key=str(MemoryKeys.GENERATED_PLAYWRIGHT_SCRIPTS),
                reader=self.NAME,
            ) or []

        if not playwright_scripts:
            output.add_warning(
                "No Playwright scripts found in memory. "
                "Ensure Automation Generator ran before this agent."
            )
            output.reasoning = (
                "No browser scripts to execute. "
                "Browser Execution Agent has nothing to run."
            )
            output.confidence = 1.0
            output.execution_mode = "skipped_no_scripts"

            await self._write_to_memory(input_data, output)
            return output

        # Check if application is reachable
        app_reachable = await self._check_application(
            input_data.base_url
        )

        if not app_reachable and not input_data.dry_run:
            output.add_warning(
                f"Application at {input_data.base_url} is not reachable. "
                f"Switching to simulation mode."
            )

        # ==================================================
        # EXECUTE TESTS
        # ==================================================

        workspace = Path(".aiqe") / "browser" / input_data.workflow_id[:8]
        workspace.mkdir(parents=True, exist_ok=True)

        screenshots_dir = workspace / "screenshots"
        screenshots_dir.mkdir(exist_ok=True)

        all_results: list[BrowserTestResult] = []

        for script_data in playwright_scripts:
            script_results = await self._execute_script(
                script_data=script_data,
                input_data=input_data,
                workspace=workspace,
                screenshots_dir=screenshots_dir,
                app_reachable=app_reachable,
            )
            all_results.extend(script_results)

        # ==================================================
        # COMPUTE STATISTICS
        # ==================================================

        output.results = [r.to_dict() for r in all_results]
        output.failed_tests = [
            r.to_dict() for r in all_results if not r.passed
        ]
        output.total_executed = len(all_results)
        output.total_passed = sum(1 for r in all_results if r.passed)
        output.total_failed = sum(1 for r in all_results if not r.passed)
        output.pass_rate = (
            output.total_passed / output.total_executed
            if output.total_executed > 0 else 0.0
        )
        output.screenshots = [
            r.screenshot_path
            for r in all_results
            if r.screenshot_path
        ]
        output.execution_mode = (
            "live" if app_reachable else "simulation"
        )

        output.reasoning = (
            f"Executed {output.total_executed} browser tests "
            f"across {len(playwright_scripts)} scripts. "
            f"Pass rate: {output.pass_rate:.0%}. "
            f"Mode: {output.execution_mode}."
        )
        output.confidence = 0.85 if app_reachable else 0.5

        if output.total_failed > 0:
            output.add_evidence(
                kind="browser_failures",
                content=(
                    f"{output.total_failed} browser tests failed. "
                    f"Screenshots captured: {len(output.screenshots)}"
                ),
                source="browser_execution_agent",
                relevance="Browser test failures requiring bug analysis",
            )

        output.suggested_next_action = (
            f"Bug Analysis Agent should examine the "
            f"{output.total_failed} browser test failures "
            f"with their screenshots and console logs."
            if output.total_failed > 0
            else "All browser tests passed."
        )

        await self._write_to_memory(input_data, output)
        return output

    async def _check_application(self, base_url: str) -> bool:
        """Check if the application is running at base_url."""
        try:
            import httpx
            async with httpx.AsyncClient(timeout=5.0) as client:
                response = await client.get(base_url)
                return response.status_code < 500
        except Exception:
            return False

    async def _execute_script(
        self,
        script_data: dict[str, Any],
        input_data: BrowserExecutionInput,
        workspace: Path,
        screenshots_dir: Path,
        app_reachable: bool,
    ) -> list[BrowserTestResult]:
        """Execute a single Playwright script file."""
        filename = script_data.get("filename", "test.py")
        feature = script_data.get("feature", "unknown")
        test_count = script_data.get("test_count", 1)

        # In dry_run mode or when app is unreachable,
        # simulate test execution with deterministic results
        if input_data.dry_run or not app_reachable:
            return self._simulate_execution(
                filename=filename,
                feature=feature,
                test_count=test_count,
                screenshots_dir=screenshots_dir,
            )

        # Try to run with actual Playwright
        try:
            return await self._run_with_playwright(
                script_data=script_data,
                input_data=input_data,
                workspace=workspace,
                screenshots_dir=screenshots_dir,
            )
        except ImportError:
            logger.warning(
                "playwright_not_installed",
                message="Install with: playwright install chromium",
            )
            output_results = self._simulate_execution(
                filename=filename,
                feature=feature,
                test_count=test_count,
                screenshots_dir=screenshots_dir,
            )
            for r in output_results:
                r.error = (
                    "Playwright not installed. "
                    "Install with: playwright install chromium"
                )
                r.passed = False
            return output_results
        except Exception as e:
            logger.error(
                "browser_execution_error",
                filename=filename,
                error=str(e),
            )
            return [BrowserTestResult(
                test_name=f"Execution failed: {filename}",
                script_file=filename,
                feature=feature,
                passed=False,
                error=str(e),
            )]

    async def _run_with_playwright(
        self,
        script_data: dict[str, Any],
        input_data: BrowserExecutionInput,
        workspace: Path,
        screenshots_dir: Path,
    ) -> list[BrowserTestResult]:
        """Execute tests using actual Playwright."""
        from playwright.async_api import async_playwright

        filename = script_data.get("filename", "test.py")
        feature = script_data.get("feature", "unknown")
        content = script_data.get("content", "")

        results = []

        async with async_playwright() as p:
            browser_launcher = getattr(p, input_data.browser_type, p.chromium)

            context_options: dict[str, Any] = {}
            if input_data.capture_video:
                context_options["record_video_dir"] = str(workspace / "videos")

            browser = await browser_launcher.launch(
                headless=input_data.headless
            )
            context = await browser.new_context(**context_options)
            page = await context.new_page()

            # Collect console logs
            console_logs: list[str] = []
            page.on("console", lambda msg: console_logs.append(
                f"{msg.type}: {msg.text}"
            ))

            # Collect network logs
            network_logs: list[dict[str, Any]] = []
            page.on("request", lambda req: network_logs.append({
                "type": "request",
                "method": req.method,
                "url": req.url,
            }))
            page.on("response", lambda res: network_logs.append({
                "type": "response",
                "status": res.status,
                "url": res.url,
            }))

            # Navigate to base URL as a basic smoke test
            with Timer() as timer:
                try:
                    await page.goto(
                        input_data.base_url,
                        timeout=input_data.timeout_seconds * 1000,
                    )
                    screenshot_path = None
                    if input_data.capture_screenshots:
                        ss_path = screenshots_dir / f"{feature}_smoke.png"
                        await page.screenshot(path=str(ss_path))
                        screenshot_path = str(ss_path)

                    results.append(BrowserTestResult(
                        test_name=f"Smoke test: {feature}",
                        script_file=filename,
                        feature=feature,
                        passed=True,
                        duration_seconds=timer.elapsed_seconds,
                        screenshot_path=screenshot_path,
                        console_logs=console_logs[:10],
                        network_logs=network_logs[:10],
                    ))

                except Exception as e:
                    screenshot_path = None
                    if input_data.capture_screenshots:
                        try:
                            ss_path = screenshots_dir / f"{feature}_failure.png"
                            await page.screenshot(path=str(ss_path))
                            screenshot_path = str(ss_path)
                        except Exception:
                            pass

                    results.append(BrowserTestResult(
                        test_name=f"Smoke test: {feature}",
                        script_file=filename,
                        feature=feature,
                        passed=False,
                        duration_seconds=timer.elapsed_seconds,
                        error=str(e),
                        screenshot_path=screenshot_path,
                        console_logs=console_logs[:10],
                    ))

            await context.close()
            await browser.close()

        return results

    def _simulate_execution(
        self,
        filename: str,
        feature: str,
        test_count: int,
        screenshots_dir: Path,
    ) -> list[BrowserTestResult]:
        """
        Simulate browser test execution for dry-run mode.

        Returns deterministic results without launching a browser.
        Used when application is not running or in dry-run mode.
        """
        results = []
        for i in range(max(1, min(test_count, 5))):
            results.append(BrowserTestResult(
                test_name=f"[SIMULATED] {feature} test {i + 1}",
                script_file=filename,
                feature=feature,
                passed=True,
                duration_seconds=0.1,
                console_logs=[
                    "[simulation] No real browser was launched",
                ],
            ))
        return results

    async def _write_to_memory(
        self,
        input_data: AgentInput,
        output: BrowserExecutionOutput,
    ) -> None:
        """Write execution results to shared memory."""
        if not self._memory:
            return

        await self._memory.set(
            key=str(MemoryKeys.BROWSER_EXECUTION_RESULTS),
            value=output.to_dict(),
            written_by=self.NAME,
        )
        await self._memory.set(
            key=str(MemoryKeys.BROWSER_FAILED_TESTS),
            value=output.failed_tests,
            written_by=self.NAME,
        )
