"""
AIQE FastAPI — Report Endpoints.

POST /workflows/{id}/report  — generate a report for a workflow
"""

from __future__ import annotations

from datetime import datetime, timezone

from fastapi import APIRouter, HTTPException, status

from aiqe.api.dependencies import AuthDep, RepositoryBundleDep
from aiqe.api.schemas import GenerateReportRequest, ReportResponse

router = APIRouter(prefix="/workflows", tags=["reports"])


@router.post(
    "/{workflow_id}/report",
    response_model=ReportResponse,
    summary="Generate a quality report",
    description=(
        "Generates a quality report for a completed workflow. "
        "Supports markdown and JSON formats. "
        "HTML/PDF reports will be available with the Report Agent (Step 18)."
    ),
)
async def generate_report(
    workflow_id: str,
    request: GenerateReportRequest,
    bundle: RepositoryBundleDep,
    auth: AuthDep,
) -> ReportResponse:
    """Generate a report for a workflow."""
    wf = await bundle.workflows.find_by_id(workflow_id)
    if wf is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail={"error": "workflow_not_found", "workflow_id": workflow_id},
        )

    bugs = await bundle.bugs.find_by_workflow(workflow_id)
    audit_entries = []
    if request.include_audit:
        audit_entries = await bundle.audit.find_by_workflow(workflow_id)

    import json as json_mod

    if request.format.value == "json":
        content = json_mod.dumps({
            "workflow": wf,
            "bugs": bugs,
            "audit_log": audit_entries,
        }, indent=2, default=str)

    elif request.format.value == "markdown":
        content = _build_markdown_report(wf, bugs, audit_entries)

    else:
        content = _build_markdown_report(wf, bugs, audit_entries)

    return ReportResponse(
        workflow_id=workflow_id,
        format=request.format.value,
        content=content,
        generated_at=datetime.now(timezone.utc).isoformat(),
    )


def _build_markdown_report(
    wf: dict,
    bugs: list,
    audit_entries: list,
) -> str:
    """Build a Markdown quality report."""
    severity_order = {
        "Critical": 0, "High": 1, "Medium": 2,
        "Low": 3, "Informational": 4,
    }

    lines = [
        "# AIQE Quality Report",
        "",
        f"**Workflow ID:** `{wf.get('id', 'N/A')}`",
        f"**Status:** {wf.get('status', 'unknown').upper()}",
        f"**Repository:** {wf.get('repository', 'N/A')}",
        f"**Branch:** {wf.get('branch', 'N/A')}",
        f"**Trigger:** {wf.get('trigger', 'N/A')}",
        "",
        "---",
        "",
        "## Executive Summary",
        "",
        "| Metric | Value |",
        "|--------|-------|",
        f"| Total Bugs | {len(bugs)} |",
        f"| Agents Completed | {wf.get('agents_completed', 0)} |",
        f"| Agents Skipped | {wf.get('agents_skipped', 0)} |",
        "",
    ]

    if bugs:
        sorted_bugs = sorted(
            bugs,
            key=lambda b: severity_order.get(b.get("severity", ""), 99),
        )

        # Bug summary by severity
        counts: dict = {}
        for bug in bugs:
            sev = bug.get("severity", "Unknown")
            counts[sev] = counts.get(sev, 0) + 1

        lines += ["## Bug Summary by Severity", ""]
        for sev in ["Critical", "High", "Medium", "Low", "Informational"]:
            if sev in counts:
                lines.append(f"- **{sev}:** {counts[sev]}")
        lines.append("")

        lines += [f"## Bug Details ({len(bugs)} total)", ""]

        for bug in sorted_bugs:
            lines += [
                f"### [{bug.get('severity')}] {bug.get('title', 'N/A')}",
                "",
                f"- **Confidence:** {bug.get('confidence', 0)*100:.0f}%",
                f"- **Feature:** {bug.get('affected_feature', 'N/A')}",
                f"- **Root Cause:** {bug.get('root_cause', 'N/A')}",
                f"- **Suggested Fix:** {bug.get('suggested_fix', 'N/A')}",
                f"- **Fix Confidence:** {bug.get('fix_confidence', 0)*100:.0f}%",
                "",
            ]

            if bug.get("is_downstream"):
                lines.append(
                    f"> ℹ️ This is a downstream effect of bug "
                    f"`{bug.get('root_bug_id', 'N/A')}`"
                )
                lines.append("")

    else:
        lines += ["## Results", "", "✅ **No bugs found in this scan.**", ""]

    lines += [
        "---",
        "",
        "> *Generated by AIQE — AI Quality Engineering Operating System*",
        "> *AIQE provides recommendations. Release decisions require human approval.*",
    ]

    return "\n".join(lines)
